config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'users/show'
  resources :events, only: [:index, :new, :create, :show, :destroy, :edit, :update]
  root to: "events#index"
  get 'event=:event_id/setup_attendances', to: 'attendances#new', as: 'setup_attendances'
  get 'event=:event_id/attendances', to: 'attendances#index', as: 'attendances'
  post 'event=:event_id/attendances', to: 'attendances#create'
  resources :attendances, only: [:destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :event
  scope :user_event, ->(user_id, event_id) { select('id').where('attendee_id = ? AND event_id = ?',
                                                                user_id, event_id)}
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :host, class_name: 'User'
  has_many :attendances
  has_many :attendees, through: :attendances
  scope :past, -> { where 'date < ?', DateTime.now }
  scope :upcoming, -> { where 'date >= ?', DateTime.now }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events, foreign_key: :host_id
  has_many :attendances, foreign_key: :attendee_id
  has_many :attended_events, through: :attendances, source: :event

  def peers
    User.all - [self]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

  def index
  end

  def new
    @event = Event.find(params[:event_id])
  end

  def create
    event = Event.find(params[:event_id])
    guests_ids = attendance_params[:guest_ids]
    non_persisted = persisted_attendances(event.id, guests_ids) - guests_ids
    if non_persisted.any?
      render attendances_path(event_id),
             alert: "System could not invite users #{non_persisted}"
    else
      redirect_to event, notice: 'Invitations were sent successfully'
    end
  end

  def destroy
    begin
      p params[:id]
      Attendance.destroy(params[:id])
      redirect_to users_show_path, notice: 'Your assistance was removed successfully'
    rescue ActiveRecord::RecordNotFound => e
      redirect_to users_show_path, alert: 'An error occurred during the deletion of this assistance'
    end
  end

  private

  def persisted_attendances(event_id, guests_ids)
    guests_ids.reduce(Array.new) do |persisted_ids, attendee_id|
      persisted_ids << attendee_id if
        Attendance.create attendee_id:, event_id: event_id
      persisted_ids
    end
  end

  def attendance_params
    permit_params = params.require(:attendance).permit(:guest_ids => [])
    sanitize_params permit_params
    permit_params
  end

  def sanitize_params(permit_params) # CHECKBOX returns empty values on unchecked
    permit_params[:guest_ids].filter! { |id| !id.empty? }
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: :index
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build event_params
    if @event.save
      redirect_to @event, notice: 'Event created successfully'
    else
      render new_event_path(@event), alert: 'Something went wrong'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def destroy
    Event.delete(params[:id])
    redirect_to users_show_path, notice: "Event #{params[:id]} deleted successfully"
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    event = Event.find(params[:id])
    if event.update event_params
      redirect_to event, notice: 'Event edited successfully'
    else
      render edit_event_path(event), alert: 'Could not update event'
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/new.html.erb
<h1>Attendance list of event: <%= @event.name %></h1>
<p>You can setup your invitations in this page</p>
<%= form_with url: attendances_path, data: { 'turbo-method': :post } do |f| %>
  <% feasible_guests = current_user.peers %>
  <%= f.collection_check_boxes 'attendance[guest_ids]', feasible_guests, :id, :email %><br>
  <%= f.submit "Send" %>
<% end %>

app/views/attendances/partials/_attended_events.html.erb
<% attended_events = current_user.attended_events %>
<% unless attended_events.empty? %>
  <h2>Attended events</h2>
  <h3>Past events</h3>
  <%= raw "<p>You haven't gone to any event yet</p>" if attended_events.past.empty? %>
  <% attended_events.past.each do |event| %>
    <p>• <%= "#{event.name}, was on #{event.date}" %></p>
    <% event_attendance = Attendance.user_event(current_user.id, event.id) %>
    <% attendance_id = event_attendance[0] %>
    <%= link_to 'Remove attendance', attendance_path(attendance_id), data: { 'turbo-method': :delete,
                                                                             turbo_confirm: 'Are you sure?' }  %>
  <% end %>
  <h3>Upcoming events</h3>
  <% attended_events.upcoming.each do |event| %>
    <p>• <%= "#{event.name}, scheduled for #{event.date}" %></p>
    <% event_attendance = Attendance.user_event(current_user.id, event.id) %>
    <% attendance_id = event_attendance[0] %>
    <%= link_to 'Remove attendance', attendance_path(attendance_id), data: { 'turbo-method': :delete,
                                                              turbo_confirm: 'Are you sure?' }  %>
  <% end %>
<% end %>

app/views/events/edit.html.erb
<h1>Edit event</h1>
<%= render 'events/partials/form', event: @event %>

app/views/events/index.html.erb
<h1>Events</h1>
<p>Look at the latest available events</p>
<%= link_to 'View my events', users_show_path %>

app/views/events/new.html.erb
<h1>New event creation</h1>
<%= form_with model: @event do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br>
  <%= f.label :description %>:
  <%= f.text_area :description %><br>
  <%= f.label :date, 'Date and Time' %>:
  <%= f.datetime_field :date %><br>
  <%= f.submit %>
<% end %>

app/views/events/partials/_event_info.html.erb
<h2>Title:</h2>
<p><%= event.name %></p>
<h2>Date:</h2>
<p><%= event.date %></p>
<h2>Description:</h2>
<p>
  <%= event.description&.empty? ? "This event has no given description" : event.description %>
</p>
<%= link_to 'Info', event %>
<%= link_to 'Delete', event, data: { "turbo-method": :delete,
                                     turbo_confirm: 'Are you sure?' }%>
<%= link_to 'Invite people', setup_attendances_path(event.id) %>
<%= link_to 'Edit', edit_event_path(event.id) %><br>

app/views/events/partials/_form.html.erb
<%= form_with model: @event do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br>
  <%= f.label :description %>:
  <%= f.text_area :description %><br>
  <%= f.label :date, 'Date and Time' %>:
  <%= f.datetime_field :date %><br>
  <%= f.submit %>
<% end %>

app/views/events/show.html.erb
<%= render "events/partials/event_info", event: @event %>
<h2>Attendees</h2>
<% @event.attendees.each_with_index do |guest, idx| %>
  <p>
    <%= "#{idx + 1}. #{guest.email}" %>
  </p>
<% end %>
<%= link_to 'Back to my events', users_show_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<ul id="navbar">
  <li>
    <span>Private Events</span>
  </li>
  <li>
    <%= link_to 'Home', root_path %>
  </li>
  <li>
    <%= link_to 'My events', users_show_path %>
  </li>
  <li>
    <%= link_to 'Logout', destroy_user_session_path, data: { 'turbo-method': :delete,
                                                             turbo_confirm: 'Are you sure?' } %>
  </li>
</ul>

app/views/users/show.html.erb
<h1>Welcome, <%= current_user.first_name %></h1>
<hr>
<% user_events = current_user.events %>
<% if user_events.size > 0 %>
  <%= link_to 'Create new event', new_event_path %>
  <h2>Here are your events</h2>
  <% user_events.each_with_index do |event, idx| %>
    <p>
      <b><%= "#{idx + 1}." %></b>
    </p>
    <%= render "events/partials/event_info", event: event %>
    <hr>
  <% end %>
<% else %>
  Seems like you haven't created any event yet<br>
  <%= link_to 'Create a new event', new_event_path %>
<% end %>
<%= render 'attendances/partials/attended_events' %>